blog/urls.py
from django.urls import path

from .views import PostsListView, PostsTagListView, PostDetailView, PostsListSearchView, PutLikeView, PutDislikeView, PutWaterView, CommentChangeView, CommentDelete
from .decorators import creator_comment_only

urlpatterns = [
    path('', PostsListView.as_view(), name='posts_list'),
    path('search/', PostsListSearchView.as_view(), name='search_blog'),
    path('tags/<slug:tag_slug>/', PostsTagListView.as_view(), name='tag_list'),
    path('<slug:post_slug>/', PostDetailView.as_view(), name='post_detail'),

    path('put_like/<int:post_pk>/', PutLikeView.as_view(), name='put_like'),
    path('put_dislike/<int:post_pk>/', PutDislikeView.as_view(), name='put_dislike'),
    path('put_water/<int:post_pk>/', PutWaterView.as_view(), name='put_water'),

    path('comment_change/<int:comment_pk>/', creator_comment_only(CommentChangeView.as_view()), name='comment_change'),
    path('comment_delete/<int:comment_pk>/', creator_comment_only(CommentDelete.as_view()), name='comment_delete'),
]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import CoursesListView, CourseDetailView, LessonDetailView


urlpatterns = [
    path('', CoursesListView.as_view(), name='courses_list'),
    path('<slug:course_slug>/', CourseDetailView.as_view(), name='course_detail'),
    path('<slug:course_slug>/lessons/<slug:lesson_slug>', login_required(LessonDetailView.as_view()), name='lesson_detail'),
]

katsu_dev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Library urls

    path("__debug__/", include("debug_toolbar.urls")),
    path('ckeditor5/', include('django_ckeditor_5.urls')),


    # Apps urls
    
    path('', include('core.urls')),
    path('courses/', include('courses.urls')),
    path('training/', include('training.urls')),
    path('blog/', include('blog.urls')),
    path('auth/', include('authorization.urls')),
    path('accounts/', include('users.urls')),
]


'''
    Отображение медиа файлов в режиме тестирования приложения (DEBUG = True)
'''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Объявление для кастомной страницы ошибки 404
handler404 = 'handlers.views.custom_404'

courses/models.py
import os

from django.db import models
from django.core.validators import FileExtensionValidator
from django.urls import reverse

from django_ckeditor_5.fields import CKEditor5Field

from users.models import User
from handlers.validators import ban_words_validator


class LessonQuestion(models.Model):
    """ Модель вопросов к уроку """
    name = models.CharField(verbose_name='Наименование вопроса', max_length=128)
    answer = models.TextField(verbose_name='Ответ на вопрос')

    class Meta:
        verbose_name = 'Вопрос к уроку'
        verbose_name_plural = 'Вопросы к уроку'

    def __str__(self):
        return self.name


class LessonMaterial(models.Model):
    """ Модель материалов к уроку (файлы) """
    class Extension(models.TextChoices):
        ZIP = "ZIP", '.zip'
        JPG = "JPG", '.jpg'
        PDF = "PDF", '.pdf'

    file = models.FileField(verbose_name='Файл', upload_to='lesson_materials/', validators=[FileExtensionValidator(['zip', 'jpg', 'pdf'])])
    extension = models.CharField(verbose_name='Тип файла', max_length=3, choices=Extension.choices)

    class Meta:
        verbose_name = 'Материал к уроку'
        verbose_name_plural = 'Материалы к уроку'

    def __str__(self):
        return self.file.name
    
    def only_filename(self):
        """ Метод возвращающий только наименование файла и его расширение, без полного пути к папке media """
        return os.path.basename(self.file.name)


class Lesson(models.Model):
    """ Модель урока раздела курса """
    name = models.CharField(verbose_name='Наименование урока', max_length=128)
    slug = models.SlugField(verbose_name='Слаг', max_length=255, unique=True, db_index=True)
    body = CKEditor5Field(verbose_name='Содержимое урока', config_name='default')
    materials = models.ManyToManyField(verbose_name='Материалы к уроку', to=LessonMaterial, blank=True)
    questions = models.ManyToManyField(verbose_name='Вопросы к уроку', to=LessonQuestion, blank=True)
    created_date = models.DateTimeField(verbose_name='Дата и время добавления', auto_now_add=True)

    class Meta:
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'
        ordering = ['created_date']

    def __str__(self):
        return self.name


class Theme(models.Model):
    """ Модель раздела курса """
    name = models.CharField(verbose_name='Наименование раздела курса', max_length=128, unique=True, db_index=True)
    description = models.CharField(verbose_name='Описание раздела', max_length=255)
    lessons = models.ManyToManyField(verbose_name='Уроки', to=Lesson)
    created_date = models.DateTimeField(verbose_name='Дата и время добавления', auto_now_add=True)

    class Meta:
        verbose_name = 'Раздел курса'
        verbose_name_plural = 'Разделы курса'
        ordering = ['created_date']

    def __str__(self):
        return self.name


class Course(models.Model):
    """ Модель курса """
    class Status(models.TextChoices):
        HIT = "HIT", 'Хит'
        UPDATE = "UPD", 'Обновлено'
        NEW = "NEW", 'Новинка'

    title = models.CharField(verbose_name='Наименование курса', max_length=128, unique=True, db_index=True)
    slug = models.SlugField(verbose_name='Слаг', max_length=255, unique=True, db_index=True)
    short_description = models.CharField(verbose_name='Краткое описание курса', max_length=255)
    full_description = models.TextField(verbose_name='Полное описание курса')
    amount_students = models.PositiveIntegerField(verbose_name='Количество учащихся на курсе', default=0)
    amount_hours = models.PositiveSmallIntegerField(verbose_name='Количество часов курса')
    poster = models.ImageField(verbose_name='Постер курса', upload_to='course_posters/')
    price = models.PositiveIntegerField(verbose_name='Цена курса', null=True, blank=True)
    discount = models.PositiveSmallIntegerField(verbose_name='Скидка на курс (%)', null=True, blank=True)
    status = models.CharField(verbose_name='Статус курса', max_length=3, choices=Status.choices, default=Status.NEW, null=True, blank=True)
    themes = models.ManyToManyField(verbose_name='Разделы курса', to=Theme)

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("course_detail", kwargs={"course_slug": self.slug})


class UsersStudyCourses(models.Model):
    """ Модель пользователей и изучаемых ими курсов """
    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)
    course = models.ManyToManyField(verbose_name='Курсы', to=Course)

    class Meta:
        verbose_name = 'Изучаемые курсы пользователей'
        verbose_name_plural = 'Изучаемые курсы пользователей'

    def __str__(self):
        return f'Курсы пользователя - {self.user.email}'


class Review(models.Model):
    """ Модель отзыва на курс """
    user = models.ForeignKey(verbose_name='Пользователь', to=User, on_delete=models.CASCADE)
    course = models.ForeignKey(verbose_name='Курс', to=Course, on_delete=models.CASCADE)
    body = models.TextField(verbose_name='Текст отзыва', validators=[ban_words_validator])
    created_date = created_date = models.DateTimeField(verbose_name='Дата и время создания отзыва', auto_now_add=True)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return f'{self.user.email} | {self.course.title} | {self.created_date}'

courses/views.py
from django.views.generic import ListView, DetailView

from .models import Course, Lesson, UsersStudyCourses


class CoursesListView(ListView):
    """ Представление для страницы сайта - «Курсы» """
    model = Course
    template_name = 'courses/courses_list.html'
    context_object_name = 'courses'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог курсов'

        return context


class CourseDetailView(DetailView):
    """ Представление для страницы отдельного выбранного курса """
    model = Course
    template_name = 'courses/course_detail.html'
    context_object_name = 'course'
    slug_url_kwarg = 'course_slug'

    def get_queryset(self):
        queryset = Course.objects.filter(slug=self.kwargs['course_slug']).prefetch_related('themes__lessons')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title

        first_theme = self.object.themes.first()
        first_lesson = first_theme.lessons.first()
        context['slug_lesson_first'] = first_lesson.slug

        return context


class LessonDetailView(DetailView):
     """ Представление для страницы отдельного урока к разделу курса """
     model = Lesson
     template_name = 'courses/lesson.html'
     context_object_name = 'lesson'
     slug_url_kwarg = 'lesson_slug'

     def get_queryset(self):
        queryset = Lesson.objects.filter(slug=self.kwargs['lesson_slug']).prefetch_related('materials', 'questions')

        return queryset

     def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        selected_course = Course.objects.prefetch_related('themes__lessons').get(slug=self.kwargs['course_slug'])

        context['title'] = self.object.name
        context['selected_course'] = selected_course

        new_study = UsersStudyCourses.objects.get_or_create(user=self.request.user)[0]
        new_study.course.add(selected_course)

        return context

courses/templates/courses/course_detail.html
{% extends "base.html" %}
{% load students_count_declination %}
{% load hours_count_declination %}
{% load static %}

{% block content %}
    <div class="course-column">
        <div class="course-flex">
            <div class="course-flex-row">
                <div class="course-flex-row-left">
                    {% if course.price %}
                        <p class="course-flex-row-left-price">Платный курс</p>
                    {% else %}
                        <p class="course-flex-row-left-price">Бесплатный курс</p>
                    {% endif %}
                    <h1 class="course-flex-row-left-title">{{ course.title }}</h1>
                    <p class="course-flex-row-left-desc">{{ course.full_description }}</p>
                    <div class="main-courses-flex-item-info">
                        <div class="main-courses-flex-item-info-item">
                            <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/time_icon.svg' %}" alt="Time">
                            <p class="course-flex-row-left-text">{{ course.amount_hours }} {{ course.amount_hours|hours_count_declination }}</p>
                        </div>
                        <div class="main-courses-flex-item-info-item">
                            <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/students_icon.png' %}" alt="Amount students">
                            <p class="course-flex-row-left-text">{{ course.amount_students }} {{ course.amount_students|students_count_declination }}</p>
                        </div>
                    </div>
                    <div class="course-flex-row-left-block">
                        {% if user.is_authenticated %}
                            <a href="{% url 'lesson_detail' course_slug=course.slug lesson_slug=slug_lesson_first %}" class="course-flex-row-left-start">Начать обучение</a>
                        {% else %}
                            <a href="{% url 'login' %}" class="course-flex-row-left-start">Начать обучение</a>
                        {% endif %}
                        <a href="{% url 'registration' %}" class="course-flex-row-left-reg">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>

        {% for theme in course.themes.all %}
            <div class="course-flex-chapter">
                <h2 class="course-flex-chapter-left-title">{{ theme.name }}</h2>
                <div class="course-flex-chapter-row">
                    <div class="course-flex-chapter-left">
                        <div class="course-flex-chapter-left-lessons">
                            <ul class="course-flex-chapter-left-lessons-list">
                                {% for lesson in theme.lessons.all %}
                                    {% if user.is_authenticated %}
                                        <li><a class="course-flex-chapter-left-lessons-list-item" href="{% url 'lesson_detail' course_slug=course.slug lesson_slug=lesson.slug %}">{{ lesson.name }}</a></li>
                                    {% else %}
                                        <li><a class="course-flex-chapter-left-lessons-list-item" href="{% url 'login' %}">{{ lesson.name }}</a></li>
                                    {% endif %}
                                    <div class="sep"></div>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="course-flex-chapter-right">
                        <p class="course-flex-chapter-right-desc">{{ theme.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="course-flex-info">
            <div class="course-flex-info-left">
                <p class="course-flex-info-left-title">Готовы начать прямо сейчас?</p>
                <p class="course-flex-info-left-text">Первый урок вас ждет!</p>
            </div>
            <div class="course-flex-info-right">
                {% if user.is_authenticated %}
                    <a class="course-flex-info-right-button" href="{% url 'lesson_detail' course_slug=course.slug lesson_slug=slug_lesson_first %}">Старт</a>
                {% else %}
                    <a class="course-flex-info-right-button" href="{% url 'login' %}">Старт</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

courses/templates/courses/courses.html
{% extends "base.html" %}
{% load students_count_declination %}
{% load hours_count_declination %}
{% load static %}


{% block content %}
    <div class="courses-flex">
        <h1 class="courses-flex-title">Курсы</h1>
        <div class="courses-flex-grid">
            {% for course in courses %}
                <div class="courses-flex-grid-item">
                    <img class="courses-flex-grid-item-logo" src="{{ course.poster.url }}" alt="Course logo">
                    <h2 class="main-courses-flex-item-name">{{ course.title }}</h2>
                        <p class="main-courses-flex-item-desc">{{ course.short_description }}</p>
                        <div class="main-courses-flex-item-info">
                            <div class="main-courses-flex-item-info-item">
                                <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/time_icon.svg' %}" alt="Time">
                                <p class="main-courses-flex-item-info-text">{{ course.amount_hours }} {{ course.amount_hours|hours_count_declination }}</p>
                            </div>
                            <div class="main-courses-flex-item-info-item">
                                <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/students_icon.png' %}" alt="Amount students">
                                <p class="main-courses-flex-item-info-text">{{ course.amount_students }} {{ course.amount_students|students_count_declination }}</p>
                            </div>
                        </div>
                        <div class="main-courses-flex-item-button-block">
                            <a class="main-courses-flex-item-button" href="#">Начать обучение</a>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

courses/templates/courses/courses_list.html
{% extends "base.html" %}
{% load students_count_declination %}
{% load hours_count_declination %}
{% load static %}


{% block content %}
    <div class="courses-flex">
        <h1 class="courses-flex-title">Курсы</h1>
        <div class="courses-flex-grid">
            {% for course in courses %}
                <div class="courses-flex-grid-item">
                    <img class="courses-flex-grid-item-logo" src="{{ course.poster.url }}" alt="Course logo">
                    <h2 class="main-courses-flex-item-name">{{ course.title }}</h2>
                        <p class="main-courses-flex-item-desc">{{ course.short_description }}</p>
                        <div class="main-courses-flex-item-info">
                            <div class="main-courses-flex-item-info-item">
                                <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/time_icon.svg' %}" alt="Time">
                                <p class="main-courses-flex-item-info-text">{{ course.amount_hours }} {{ course.amount_hours|hours_count_declination }}</p>
                            </div>
                            <div class="main-courses-flex-item-info-item">
                                <img class="main-courses-flex-item-info-image" src="{% static 'img/UX/students_icon.png' %}" alt="Amount students">
                                <p class="main-courses-flex-item-info-text">{{ course.amount_students }} {{ course.amount_students|students_count_declination }}</p>
                            </div>
                        </div>
                        <div class="main-courses-flex-item-button-block">
                            <a class="main-courses-flex-item-button" href="{{ course.get_absolute_url }}">Начать обучение</a>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

courses/templates/courses/lesson.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="lesson-flex">
        <div class="lesson-flex-nav">
            {% for theme in selected_course.themes.all %}
                <div class="lesson-flex-nav-item">
                    <h1 class="lesson-flex-nav-title">{{ theme.name }}</h1>
                    <ul class="lesson-flex-nav-list">
                        {% for lesson in theme.lessons.all %}
                        <li><a href="{% url 'lesson_detail' course_slug=selected_course.slug lesson_slug=lesson.slug %}" class="lesson-flex-nav-list-item">{{ lesson.name }}</a></li>
                        <div class="sep"></div>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        <div class="lesson-flex-wrapper">
            <div class="lesson-flex-item">
                <h2 class="lesson-flex-item-title">{{ lesson.name }}</h2>
                <div class="sep"></div>
                <p class="lesson-flex-item-text">{{ lesson.body|safe }}</p>
            </div>

            {% if lesson.questions.all %}
                <div class="lesson-flex-wrapper-questions">
                    <h3 class="lesson-flex-wrapper-questions-title">Вопросы к уроку</h3>
                    <div class="sep"></div>
                    {% for question in lesson.questions.all %}
                        <div class="lesson-flex-wrapper-questions-item">
                            <p class="lesson-flex-wrapper-questions-item-title">{{ question.name }}</p>
                            <details>
                                <summary class="lesson-flex-wrapper-questions-item-legend">Показать ответ</summary>
                                <p class="lesson-flex-wrapper-questions-item-answer">{{ question.answer }}</p>
                            </details>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            {% if lesson.materials.all %}
                <div class="lesson-flex-wrapper-questions">
                    <h3 class="lesson-flex-wrapper-questions-title">Материалы к уроку</h3>
                    <div class="sep"></div>
                    {% for material in lesson.materials.all %}
                        <div class="lesson-flex-wrapper-questions-file">
                            {% if material.get_extension_display == '.zip' %}
                                <img class="lesson-flex-wrapper-questions-file-icon" src="{% static 'img/files_extensions_icons/archive_icon.png' %}" alt="ZIP file">
                            {% elif material.get_extension_display == '.jpg' %}
                                <img class="lesson-flex-wrapper-questions-file-icon" src="{% static 'img/files_extensions_icons/jpg_icon.png' %}" alt="JPG file">
                            {% else %}
                                <img class="lesson-flex-wrapper-questions-file-icon" src="{% static 'img/files_extensions_icons/pdf_icon.png' %}" alt="PDF file">
                            {% endif %}
                            <a class="lesson-flex-wrapper-questions-file-link" href="{{ material.file.url }}" download rel="noopener">{{ material.only_filename }}</a>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}